name: 'Check Critical Files'
description: '👁 Check for critical files in your commits and warns you'
branding:
  icon: 'alert-circle'
  color: 'gray-dark'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  critical_files:
    description: 'A newline separated list of critical files'
    required: true
  critical_files_commited_message:
    description: 'Message to show when listing all commited critical files'
    required: false
    default: 'Caution! you have commited some critical files'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.critical_files }}
    - ${{ inputs.critical_files_commited_message }}

